services:
  - type: web
    name: robo-coleta-server
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn server.app:app
    envVars:
      - key: FIREBASE_DB_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
